swagger: '2.0'
info:
  title: API Proposal for transactions
  version: 1.0.0
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /Account:
    post:
      tags:
        - Account 
      summary: Get account information by userId
      parameters:
        - name: body
          in: body
          description: ID of the user
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
      security:
        - Bearer: []
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              accountId:
                type: integer
              balance:
                type: integer
        '400':
          description: Invalid request
        '500':
          description: Internal server error
        default:
          description: Unexpected error
  /Transaction:
    post:
      tags:
        - Transaction
      summary: Retrieve transaction list for the current month, by account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: body
          in: body
          description: ID of the user
          required: true
          schema:
            type: object
            properties:
              account_id:
                type: integer
      security:
        - Bearer: []
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                date:
                  type: string
                recipient:
                  type: string
                amount:
                  type: integer
                balanceAfterTransaction:
                  type: integer
                accountId:
                  type: integer
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error
        default:
          description: Unexpected error
  /Transaction/details/{transactionId}:
    post:
      tags:
        - Transaction
      summary: Retrieve transaction details by id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: Id of the transaction that needs to be edited
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                type:
                  type: string
                category:
                  type: string
                note:
                  type: string
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error
        default:
          description: Unexpected error
  /Transaction/{transactionId}:
    put:
      tags:
        - Transaction
      summary: Update a transaction's note/category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: Id of the transaction that needs to be edited
          required: true
          type: string
        - name: body
          in: body
          description: ID of the transaction
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
              newCategory: 
                type: string
              newNote: 
                type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error
        default:
          description: Unexpected error
  /Transaction/category/{transactionId}:
    delete:
      tags:
        - Transaction
      summary: Delete a category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: Id of the transaction
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error
        default:
          description: Unexpected error
  /Transaction/note/{transactionId}:
    delete:
      tags:
        - Transaction
      summary: Delete a note
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: Id of the transaction that needs to be edited
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error
        default:
          description: Unexpected error